from __future__ import annotations

import enum

# DO NOT EDIT!
# This file was automatically generated by "generate_ids.py"


class RLUnitTypeId(enum.Enum):
    
    RL_MARINE = 1970
    RL_STALKER = 1970
    RL_ZEALOT = 1971

    def __repr__(self) -> str:
        return f"RLUnitTypeId.{self.name}"


for item in RLUnitTypeId:
    globals()[item.name] = item
